### ISSUE TITLE
Spurious unknown Dialect Error.

### ISSUE THREAD

**Issue by lloydtabb** [looker-open-source/malloy#151]
Doesn't run, stack trace below.  Error message

 Unknown Dialect undefined dialect

```
        query: q is table('malloytest.aircraft')->{
          group_by: state
        }

        explore: r is from(->q){
          query: foo is {
            group_by: state
          }
        }

        query: r->foo
```

**Comment by mtoy-googly-moogly** [comment]
stack trace, error text?

**Comment by lloydtabb** [comment]
```
      at Object.getDialect (../malloy/src/dialect/dialect_map.ts:23:11)
      at new QueryStruct (../malloy/src/model/malloy_query.ts:2608:20)
      at Function.nextStructDef (../malloy/src/model/malloy_query.ts:1125:16)
      at Object.outputSpace (../malloy/src/lang/ast/ast-main.ts:1172:29)
      at PipelineDesc.appendOps (../malloy/src/lang/ast/ast-main.ts:1372:21)
      at PipelineDesc.getPipelineForExplore (../malloy/src/lang/ast/ast-main.ts:
```

**Comment by mtoy-googly-moogly** [comment]
Fixed
