### ISSUE TITLE
VSCode: command 'malloy.editConnections' not found

### ISSUE THREAD

**Issue by lazarevskiVsg** [looker-open-source/malloy#238]
I was doing everything according to README. "Edit connections" does nothing. VSCode 1.63.2

```
[2022-01-25 00:22:14.861] [renderer1] [error] command 'malloy.editConnections' not found: Error: command 'malloy.editConnections' not found
    at y._tryExecuteCommand (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1482:3364)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1482:3245
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async n.open (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:577:70656)
    at async s.open (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:577:72529)

```

**Comment by anikaks** [comment]
Hey @lazarevskiVsg thanks for filing; we think we know what's going on here and are fixing. 

If you open / create a .malloy file and then try to click "Edit Connections," does that work for you?

**Comment by christopherswenson** [comment]
I believe this is the same issue as https://github.com/looker-open-source/malloy/issues/239

**Comment by jonathanswenson** [comment]
> As a temporary workaround, if you open / create a .malloy file and then try to click "Edit Connections," does that work for you?

this workaround worked for me.

**Comment by lazarevskiVsg** [comment]
> As a temporary workaround, if you open / create a .malloy file and then try to click "Edit Connections," does that work for you?
Yes, it works, thanks!

**Comment by anikaks** [comment]
@lazarevskiVsg this should now be resolved; to ensure you're on the latest version of the plugin you will need to restart VSCode. Closing the issue now but let us know if this isn't resolved for you!
