### ISSUE TITLE
If you don't have a workspace open, connections wont save

### ISSUE THREAD

**Issue by bporterfield** [looker-open-source/malloy#256]
Talk to Jonathan :D

**Comment by jonathanswenson** [comment]
At some point I ran into this. I believe that the “save” button disappeared which implied that the save was successful, but I was then unable to see the connection in the connection panel and unable to use it and was not present if I re-opened the edit connection page. 

I think this was the stack trace that I got when this happened one of the times I tried this: 
```
ERR Unable to write to Workspace Settings because no workspace is opened. Please open a workspace first and try again.: Error: Unable to write to Workspace Settings because no workspace is opened. Please open a workspace first and try again.
    at E.toConfigurationEditingError (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1887:13054)
    at E.validate (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1887:16141)
    at E.doWriteConfiguration (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1887:9415)
    at Object.factory (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1887:9249)
    at b.consume (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:77:15641)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:77:15456
    at new Promise (<anonymous>)
    at b.queue (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:77:15380)
    at E.writeConfiguration (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1887:9234)
    at P.writeConfigurationValue (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1887:42048)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1887:27769
    at Array.map (<anonymous>)
    at P.updateValue (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1887:27757)
workbench.desktop.main.css:1 
```

**Comment by christopherswenson** [comment]
Possible resources: 
* https://stackoverflow.com/a/68600738
* https://code.visualstudio.com/api/references/vscode-api
