### ISSUE TITLE
Unknown dialect ~malformed~

### ISSUE THREAD

**Issue by christopherswenson** [looker-open-source/malloy#580]
Will update this with more info as soon as I can...

Here's a stack trace (minified/packaged code, sorry, will try to reproduce unminified later):

```
Error: Unknown Dialect ~malformed~
    at d6e (/malloy/demo/malloy-demo-composer/dist/malloy-composer-demo-darwin-x64/malloy-composer-demo.app/Contents/Resources/app/build/main.js:228:242)
    at kg.getDialect (/malloy/demo/malloy-demo-composer/dist/malloy-composer-demo-darwin-x64/malloy-composer-demo.app/Contents/Resources/app/build/main.js:446:96383)
    at OG.getDialect (/malloy/demo/malloy-demo-composer/dist/malloy-composer-demo-darwin-x64/malloy-composer-demo.app/Contents/Resources/app/build/main.js:446:103975)
    at yY.getExpression (/malloy/demo/malloy-demo-composer/dist/malloy-composer-demo-darwin-x64/malloy-composer-demo.app/Contents/Resources/app/build/main.js:453:118838)
    at CK.queryFieldDef (/malloy/demo/malloy-demo-composer/dist/malloy-composer-demo-darwin-x64/malloy-composer-demo.app/Contents/Resources/app/build/main.js:453:31948)
    at CK.fieldDef (/malloy/demo/malloy-demo-composer/dist/malloy-composer-demo-darwin-x64/malloy-composer-demo.app/Contents/Resources/app/build/main.js:453:31872)
    at TG.fieldDef (/malloy/demo/malloy-demo-composer/dist/malloy-composer-demo-darwin-x64/malloy-composer-demo.app/Contents/Resources/app/build/main.js:446:94822)
    at kg.structDef (/malloy/demo/malloy-demo-composer/dist/malloy-composer-demo-darwin-x64/malloy-composer-demo.app/Contents/Resources/app/build/main.js:446:100173)
    at WG.withParameters (/malloy/demo/malloy-demo-composer/dist/malloy-composer-demo-darwin-x64/malloy-composer-demo.app/Contents/Resources/app/build/main.js:453:3499)
    at GG.execute (/malloy/demo/malloy-demo-composer/dist/malloy-composer-demo-darwin-x64/malloy-composer-demo.app/Contents/Resources/app/build/main.js:453:2296)
```

**Comment by mtoy-googly-moogly** [comment]
Is the source code which causes this available?

**Comment by mtoy-googly-moogly** [comment]
cool, just needed to know if it was valid malloy

**Comment by mtoy-googly-moogly** [comment]
so if i compile flights but never return any schema i should see this error?

**Comment by christopherswenson** [comment]
I think that should reproduce it? LMK if that doesn't work...

**Comment by christopherswenson** [comment]
One way to do that is to just `gcloud config unset project --installation` (and maybe also `gcloud config unset project`)
