### ISSUE TITLE
Circular dependencies in imports sometimes breaks the build

### ISSUE THREAD

**Issue by bporterfield** [looker-open-source/malloy#85]
NOTE: references to code here are from #71.
---

I'm encountering a bug that appears to be tied to load order and circular dependencies of imports in `lang`. I've isolated the issue in this branch. Mostly the changes consists of deleting extraneous things (calls to run queries, etc) so that the issue can be isolated.

clone this branch and `yarn; yarn build`. then run this single test:
```
yarn workspace malloy jest /field-symbols.spec.ts
```

This test completes successfully. Now comment out line 65 in `malloy_query` - this is a dummy line I've added to instantiate a MalloyTranslator. So, we're just removing the lines that instantiate a MalloyTranslator in this class:

```
const parse = new MalloyTranslator("internal://query/1", {
  URLs: { ["internal://query/1"]: "test" },
});
```

Re-run the test:

```
yarn run v1.22.10
$ /Users/bporterfield/dev/malloy/node_modules/.bin/jest /field-symbols.spec.ts
 FAIL  src/lang/field-symbols.spec.ts
  ● Test suite failed to run

    TypeError: Class extends value undefined is not a constructor or null

      131 | }
      132 |
    > 133 | class ConstantFieldSpace extends FieldSpace {
          |                                  ^
      134 |   constructor() {
      135 |     super({
      136 |       type: "struct",

      at Object.<anonymous> (src/lang/ast/ast-expr.ts:133:34)
      at Object.<anonymous> (src/lang/ast/index.ts:16:1)
      at Object.<anonymous> (src/lang/field-space.ts:17:1)
      at Object.<anonymous> (src/lang/space-field.ts:16:1)
      at Object.<anonymous> (src/lang/field-symbols.spec.ts:15:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.168 s
Ran all test suites matching /\/field-symbols.spec.ts/i.
```

This message appears to be indicative of [circular references](https://stackoverflow.com/a/44727578), and note that those references can be imports, not just types. [Here](https://medium.com/visual-development/how-to-fix-nasty-circular-dependency-issues-once-and-for-all-in-javascript-typescript-a04c987cf0de) is an article about the issue, and [another follow-up article](https://medium.com/@daveperipatus/heres-how-to-scale-this-pattern-to-larger-projects-8227eb45e1cc) that does make some sense to me.

How would removing this reference in a completely different class impact this test? The test in question loads `space-field.ts`, which then loads `malloy_query.ts`. In today's world, `malloy_query.ts` then loads up `MalloyTranslator`, which must additionally must include some classes that otherwise are not yet defined in a different loading context. Once `MalloyTranslator` no longer happens to be loaded in `malloy_query.ts`, the order of imports seems to result in the issue described in [the article](https://medium.com/visual-development/how-to-fix-nasty-circular-dependency-issues-once-and-for-all-in-javascript-typescript-a04c987cf0de):

![1_IExKTc3Mry-XzX-t-yOJ8A](https://user-images.githubusercontent.com/108260/138574526-740c0028-2be1-415b-a734-9995df8f2457.png)

I've also added the [Madge](https://github.com/pahen/madge) package in this branch, which can be used to detect circular dependencies. Here is the output:
```
➜  malloy git:(circularReferenceBug) ✗ yarn madge --extensions ts,tsx,js,jsx --circular packages/malloy/src
yarn run v1.22.10
$ /Users/bporterfield/dev/malloy/node_modules/.bin/madge --extensions ts,tsx,js,jsx --circular packages/malloy/src
Processed 47 files (1.8s) (35 warnings)

✖ Found 6 circular dependencies!

1) db/bigquery.ts > malloy.ts
2) lang/ast/index.ts > lang/ast/ast-main.ts
3) lang/field-space.ts > lang/space-field.ts
4) lang/lib/Malloy/MalloyParser.ts > lang/lib/Malloy/MalloyListener.ts
5) lang/lib/Malloy/MalloyParser.ts > lang/lib/Malloy/MalloyVisitor.ts
6) lang/ast/index.ts > lang/ast/ast-time-expr.ts
```

Node describes how this issue can happen [here](https://nodejs.org/api/modules.html#modules_cycles), and they also mention that "Careful planning is required to allow cyclic module dependencies to work correctly within an application.". It's unclear to me what other JS runtimes do under the same conditions, but we may see more of these issues if we attempt to run in-browser, for ex.

I imagine we will hit new similar issues if we don't add `madge` to our tests and have some strategy for ordering imports, perhaps as suggested by [the second article](https://medium.com/@daveperipatus/heres-how-to-scale-this-pattern-to-larger-projects-8227eb45e1cc). I attempted to resolve the issues myself, but there are a lot of import references between classes or functions in `/ast`, `space-field.ts`, and `field-space.ts`, `malloy_types.ts` and `malloy_query.ts` and I'm unsure what the best organization might be. Happy to help work / implement potential solutions.

**Comment by bporterfield** [comment]
Sounds like @mtoy-googly-moogly has a handle on this now, closing
