### ISSUE TITLE
Malloy as a library doesn't work

### ISSUE THREAD

**Issue by blackrez** [looker-open-source/malloy#873]
Hello,

I'm trying to use the npm package and follow the documentation but I've got an error at the execution.

```
import { Runtime } from "@malloydata/malloy";
import { DuckDBConnection } from "@malloydata/db-duckdb";

const connection = new DuckDBConnection("duckdb-example");
const runtime = new Runtime(connection);

runtime.loadModel("source: flights is table('duckdb:data/flights.parquet')")

const runner = runtime.loadQuery("query: flights->{group_by: flight_num}")
runner.run() // <- executes query, returns JSON of results
```

```
(base) nabil in ~/project/monplein/prototype2 on main ● ● λ node index.mjs
/Users/nabil/project/monplein/prototype2/node_modules/@malloydata/malloy/dist/malloy.js:75
                    throw new MalloyError(`Error(s) compiling model:\n${errText}`, errors);
                          ^

MalloyError: Error(s) compiling model:
FILE: internal://internal.malloy
line 1: Undefined source 'flights'
  | query: flights->{group_by: flight_num}
  |        ^
    at Malloy.compile (/Users/nabil/project/monplein/prototype2/node_modules/@malloydata/malloy/dist/malloy.js:75:27)
    at ModelMaterializer._materialize (/Users/nabil/project/monplein/prototype2/node_modules/@malloydata/malloy/dist/malloy.js:1283:27)
    at ModelMaterializer.rematerialize (/Users/nabil/project/monplein/prototype2/node_modules/@malloydata/malloy/dist/malloy.js:1464:34)
    at ModelMaterializer.materialize (/Users/nabil/project/monplein/prototype2/node_modules/@malloydata/malloy/dist/malloy.js:1459:25)
    at QueryMaterializer._materialize (/Users/nabil/project/monplein/prototype2/node_modules/@malloydata/malloy/dist/malloy.js:1494:32)
    at QueryMaterializer.rematerialize (/Users/nabil/project/monplein/prototype2/node_modules/@malloydata/malloy/dist/malloy.js:1464:34)
    at QueryMaterializer.materialize (/Users/nabil/project/monplein/prototype2/node_modules/@malloydata/malloy/dist/malloy.js:1459:25)
    at PreparedResultMaterializer._materialize (/Users/nabil/project/monplein/prototype2/node_modules/@malloydata/malloy/dist/malloy.js:1745:32)
    at PreparedResultMaterializer.rematerialize (/Users/nabil/project/monplein/prototype2/node_modules/@malloydata/malloy/dist/malloy.js:1464:34)
    at PreparedResultMaterializer.materialize (/Users/nabil/project/monplein/prototype2/node_modules/@malloydata/malloy/dist/malloy.js:1459:25) {
  log: [
    {
      at: {
        url: 'internal://internal.malloy',
        range: {
          start: { line: 0, character: 7 },
          end: { line: 0, character: 14 }
        }
      },
      message: "Undefined source 'flights'"
    }
  ]
}

Node.js v18.8.0
```

**Comment by christopherswenson** [comment]
It appears that documentation is incorrect. Here's an updated version:

```
import { Runtime } from "@malloydata/malloy";
import { DuckDBConnection } from "@malloydata/db-duckdb";

const connection = new DuckDBConnection("duckdb-example");
const runtime = new Runtime(connection);

const runner = runtime
  .loadModel("source: flights is table('duckdb:data/flights.parquet')")
  .loadQuery("query: flights->{group_by: flight_num}")
runner.run() // <- executes query, returns JSON of results
```

**Comment by christopherswenson** [comment]
Ah actually I found where that snippet was. It was incorrect, and has since been updated: https://github.com/looker-open-source/malloy/commit/4435680508647933e69cf3d6f1d0099a53f9ca53. Sorry for the confusion.

**Comment by blackrez** [comment]
Thanks, I forgot to specify where I found the code. 

Is the npm page of malloy will be updated ?

Now I have a segfault but it's an another error.

```
(base) nabil in ~/project/monplein/prototype2 on main ● ● λ node index.mjs
[1]    91358 segmentation fault  node index.mjs
```

**Comment by christopherswenson** [comment]
I believe we will be updating the NPM page soon @whscullin?

The segfault looks like https://github.com/looker-open-source/malloy/issues/798

**Comment by blackrez** [comment]
Thanks for the clarification. Now it works as attended.

**Comment by whscullin** [comment]
I've updated the npm packages so the docs on npmjs.com are now up to date, as well.
